### ISSUE TITLE
always `transaction not finalized yet`

### ISSUE THREAD

**Issue by trybye** [ilkamo/jupiter-go#17]
Is fee too low or some wrong with rpc?How to add fee?

**Comment by ilkamo** [comment]
Hi @trybye, it is hard to help because you provided no context/logs.

You can try to set the `PrioritizationFeeLamports` in the following way:

```
// More info: https://station.jup.ag/docs/apis/troubleshooting
prioritizationFeeLamports := jupiter.SwapRequest_PrioritizationFeeLamports{}
if err := prioritizationFeeLamports.UnmarshalJSON([]byte(`1`)); err != nil {
    return SwapResponse{}, fmt.Errorf("could not unmarshal prioritizationFeeLamports: %w", err)
}
```

and then pass it in the swap request:

```
jupiter.PostSwapJSONRequestBody{
    PrioritizationFeeLamports: &prioritizationFeeLamports,
    ....
}
```

You could also try to set the PrioritizationFeeLamports to `{ autoMultiplier: 2 }` or `"auto"` as mentioned in the official documentation: https://station.jup.ag/docs/apis/troubleshooting#transaction-confirmation-timeout.

If this doesn't help, try to use the https://dev.helius.xyz/ RPC, there is a free version.
